import axios from 'axios'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import Header from '../components/Header'
import { AuthProvider, getUser } from '../contexts/Auth.context'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  const preloadedAuth = { status: 'SIGNED_OUT', user: null }
  const [auth, setAuth] = useState(preloadedAuth)

  useEffect(() => {
    checkAuth()
  }, [])

  async function checkAuth() {
    return await getUser().then(auth => setAuth(auth))
  }

  return (
    <React.Fragment>
      <Head>
        <meta charset='utf-8' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <title>Next.js app</title>
      </Head>
      <AuthProvider myAuth={{ auth, checkAuth }}>
        <Header />
        <Component {...pageProps} />
      </AuthProvider>
    </React.Fragment>
  )
}

export default MyApp
