import Head from 'next/head'
import React from 'react'

export default function Home(req, res) {
  return (
    <React.Fragment>
      <Head>
        <meta charset='utf-8' />
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <span style={{ fontSize: '5rem' }}>Hello!</span>
    </React.Fragment>
  )
}
