import Head from 'next/head'

export const getServerSideProps = async ctx => {
  const { req, res } = ctx
  const { cookies } = req

  const user = JSON.parse(cookies.user)

  return { props: { user } }
}

export default function Home(req, res) {
  return (
    <>
      <Head>
        <meta charset='utf-8' />
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <span style={{ fontSize: '5rem' }}>Hello!</span>
    </>
  )
}
